#!/bin/bash
#Some housekeeping
[[ -z $_k_help ]] && export _k_help=()
### Define Aliases
export LS_COLORS='di=34:ln=35:so=32:pi=33:ex=31:bd=31:cd=31:su=31:sg=31:tw=31:ow=31'
alias mkdir='mkdir -pv'                    # Preferred 'mkdir' implementation
alias less='less -FSRXc'                    # Preferred 'less' implementation
alias c='clear'                             # c:            Clear terminal display
alias path='echo -e ${PATH//:/\\n}'         # path:         Echo all executable Paths
alias show_options='shopt'                  # Show_options: display bash options settings
alias fix_stty='stty sane'                  # fix_stty:     Restore terminal settings when screwed up
alias cd..='cd ..'
alias cls='clear'
alias pwdln='pwd -P'
alias dkr='docker'
alias d=docker
alias dokcer='docker'
alias kctl='kubectl'
alias k='kubectl'
alias g='git'
# Built 'cp' from scratch with Advanced mod: https://github.com/jarun/advcpmvn
#alias cp='cp_adv_mod_8.32 -g'
#alias mv='mv_adv_mod_8.32 -g'
alias rm="echo Use del/trash. /bin/rm is aliased to xxrm"
alias xxrm='/bin/rm'
alias grm="rm"
# If you're having SpaceVim issues with NVim, disable nvim aliases
alias vim='nvim'
alias e='nvim'
alias vi='nvim'
alias vimdiff='nvim -d'
alias incognito=' unset HISTFILE'
alias nohist=' unset HISTFILE'

## Awesome Rusted Tools
alias fd='fd -H'
alias cat='bat' # Using the Bat tool instead of cat

# Unalias ls and ll
alias ls='exa'
alias ll='exa -Flh --color=auto --icons' # Preferred 'ls' implementation
#alias ll='ls -Flh' # Preferred 'ls' implementation
alias ps='procs' # https://github.com/dalance/procs
alias top='btm' # CompNletion installed in ~/.oh-my-zsh/completions
alias sd='sd' # Sed replacement https://github.com/chmln/sd
alias du='dust -r' # https://github.com/bootandy/dust
# Another one https://github.com/nachoparker/dutree
alias cloc='tokei'
alias bench='hyperfine'
alias q='pueue'
alias rgv='rg -v "rg " | rg'
alias rgi='rg -i'
alias pdfview='evince'
alias rsync='rsync -azvhP' # [a]rchive (to preserve attributes) and compressed ([z]ipped) mode with [v]erbose and [h]uman-readable [P]rogress

### Define Functions
function show_tcp_ports {
  # netstat -tulpn
  netstat --tcp --udp --progam --numeric --listening
}

function myip {
  curl -L ifconfig.me
}


function extract {
  if [ -z "$1" ]; then
    # display usage if no parameters given
    echo "Usage: extract <path/file_name>.<zip|rar|bz2|gz|tar|tbz2|tgz|Z|7z|xz|ex|tar.bz2|tar.gz|tar.xz|.zlib|.cso>"
    echo "       extract <path/file_name_1.ext> [path/file_name_2.ext] [path/file_name_3.ext]"
  else
    for n in "$@"
    do
      if [ -f "$n" ] ; then
          case "${n%,}" in
             *.cbt|*.tar.bz2|*.tar.gz|*.tar.xz|*.tbz2|*.tgz|*.txz|*.tar)
                          tar xvf "$n"       ;;
             *.lzma)      unlzma ./"$n"      ;;
             *.bz2)       bunzip2 ./"$n"     ;;
             *.cbr|*.rar) unrar x -ad ./"$n" ;;
             *.gz)        gunzip ./"$n"      ;;
             *.cbz|*.epub|*.zip) unzip ./"$n"   ;;
             *.z)         uncompress ./"$n"  ;;
             *.7z|*.apk|*.arj|*.cab|*.cb7|*.chm|*.deb|*.dmg|*.iso|*.lzh|*.msi|*.pkg|*.rpm|*.udf|*.wim|*.xar)
                          7z x ./"$n"        ;;
             *.xz)        unxz ./"$n"        ;;
             *.exe)       cabextract ./"$n"  ;;
             *.cpio)      cpio -id < ./"$n"  ;;
             *.cba|*.ace) unace x ./"$n"     ;;
             *.zpaq)      zpaq x ./"$n"      ;;
             *.arc)       arc e ./"$n"       ;;
             *.cso)       ciso 0 ./"$n" ./"$n.iso" && \
                              extract "$n.iso" && \rm -f "$n" ;;
             *.zlib)      zlib-flate -uncompress < ./"$n" > ./"$n.tmp" && \
                              mv ./"$n.tmp" ./"${n%.*zlib}" && rm -f "$n"   ;;
             *)
                          echo "extract: '$n' - unknown archive method"
                          return 1
                          ;;
          esac
      else
          echo "'$n' - file doesn't exist"
          return 1
      fi
    done
  fi
}

function randpw { < /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c${1:-8};echo;}
function randpws { </dev/urandom tr -dc '12345!@#$%^&*-=+.<>_A-Z-a-z-0-9'|head -c${1:-8};echo;}
mcd () { mkdir -p "$1" && cd "$1" || exit; }        # mcd:          Makes new Dir and jumps inside

### Exports
[[ "${PATH#*:$HOME/.local/bin}" == "$PATH" ]] && export PATH="$PATH:$HOME/.local/bin"
[[ "${PATH#*:${KREW_ROOT:-$HOME/.krew}/bin}" == "$PATH" ]] && export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"

export EDITOR=nvim
export VISUAL=nvim

## Source k3d completion
# shellcheck disable=SC1090
[[ $(command -v k3d) ]] && . <(k3d completion zsh)
[[ $(command -v kubectl) ]] && . <(kubectl completion zsh)
[[ $(command -v starship) ]] && eval "$(starship init zsh)"

## Source Git Extras

[[ -f /usr/share/doc/git-extras/git-extras-completion.zsh ]] && source /usr/share/doc/git-extras/git-extras-completion.zsh
