---
version: "3"
services:
  endlessh:
    image: lscr.io/linuxserver/endlessh:latest
    container_name: endlessh
    environment:
      - PUID=1000
      - PGID=1000
      - MSDELAY=10000 #optional
      - MAXLINES=32 #optional
      - MAXCLIENTS=4096 #optional
      - LOGFILE=false #optional
      - BINDFAMILY= #optional
    volumes:
      - /mnt/sdcard/docker-data/endless-ssh/=/config #optional
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 22:2222
    restart: unless-stopped
