
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use the ref you want to point at
    hooks:
    - id: detect-private-key
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-json
    - id: check-merge-conflict
    - id: check-shebang-scripts-are-executable
    - id: check-symlinks
    - id: check-yaml
    - id: fix-byte-order-marker
    - id: check-ast
    - id: fix-encoding-pragma
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: mixed-line-ending
  - repo: https://github.com/python-poetry/poetry
    rev: ''  # add version here
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: ["-f", "requirements.txt", "-o", "requirements.txt"]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: "isort (python)"
        types: [python]
        args: [--add-import, from __future__ import annotations]
        exclude: |
          (?x)(
             ^(install|get)-poetry.py$
              | ^src/poetry/__init__.py$
          )
      - id: isort
        name: "isort (pyi)"
        types: [pyi]
        args: [--lines-after-imports, "-1"]

  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
